### ISSUE TITLE
Unlock new seeds over time.

### ISSUE THREAD

**Issue by McPalm** [michielbos/HorseMoon#16]
awesome. Lets see. I want
Carrot, corn,strawberry, blueberry and oats to be unlocked from the start.
watermelon, blueberry, eggplant, grapes, pumpkin to be unlocked.
in that order.
And we can later add some requirements for the got new seeds dialogue to show up.
actually, just like a new seed every 3 days or something.

**Comment by McPalm** [comment]
Imma conitnue the way dmDash did it.

**Comment by dmDash** [comment]
Seeds are unlocked by:

Watermelon: Satchel.Forest.Opened
-Visit the forest for the first time.

Blueberry: Well.Broken
-Fix the well.

Eggplant: TenderTill.RootCheck.Finish
-Sell 30 carrots while the DeepRootedIssues quest is active.

Grape: TenderTill.Filler8.Talk
-Read Tender Till's last filler dialogue.

Pumpkin: TenderTill.Salad.Yay
-Make TenderTill's blueberry salad.
